/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donniestaskv1.pkg1;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.*;
import sun.audio.*;
import java.io.*;
import java.text.AttributedCharacterIterator;

/**
 *
 * @author Stoian
 */
public class Frame extends javax.swing.JFrame {
    int hoursCounterStopwatch = 0;
    int secondsCounterStopwatch = 0;
    int minutesCounterStopwatch = 0;
    Timer stopwatch = new Timer();
    TimerTask stopwatchTask = new TimerTask()
    {
        public void run()
        {
            if(secondsCounterStopwatch<60){
                txtFieldSecondsStopwatch.setText("" + secondsCounterStopwatch);
                secondsCounterStopwatch++;
            }
            else{
                minutesCounterStopwatch++;
                secondsCounterStopwatch = 0;
                txtFieldMinutesStopwatch.setText("" + minutesCounterStopwatch);
                txtFieldSecondsStopwatch.setText("" + secondsCounterStopwatch);
                secondsCounterStopwatch++;
            }
        }
    };
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        EnterPages.setVisible(false);
        labelIntroEnterPages.setVisible(false);
        labelShowingTimeRequired.setVisible(false);
        buttonStartingBigTimer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIntroStopwatch = new javax.swing.JLabel();
        txtFieldSecondsStopwatch = new javax.swing.JTextField();
        startStop = new javax.swing.JToggleButton();
        txtFieldMinutesStopwatch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelIntroEnterPages = new javax.swing.JLabel();
        EnterPages = new javax.swing.JTextField();
        buttonStartingBigTimer = new javax.swing.JButton();
        labelShowingTimeRequired = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelIntroStopwatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIntroStopwatch.setText("За колко време прочиташ една страница?");
        labelIntroStopwatch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtFieldSecondsStopwatch.setEditable(false);
        txtFieldSecondsStopwatch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFieldSecondsStopwatch.setText("0");
        txtFieldSecondsStopwatch.setMaximumSize(new java.awt.Dimension(20, 22));
        txtFieldSecondsStopwatch.setMinimumSize(new java.awt.Dimension(20, 22));
        txtFieldSecondsStopwatch.setPreferredSize(new java.awt.Dimension(20, 22));
        txtFieldSecondsStopwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSecondsStopwatchActionPerformed(evt);
            }
        });

        startStop.setText("Старт");
        startStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopActionPerformed(evt);
            }
        });

        txtFieldMinutesStopwatch.setEditable(false);
        txtFieldMinutesStopwatch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFieldMinutesStopwatch.setText("0");
        txtFieldMinutesStopwatch.setMaximumSize(new java.awt.Dimension(20, 22));
        txtFieldMinutesStopwatch.setMinimumSize(new java.awt.Dimension(20, 22));
        txtFieldMinutesStopwatch.setPreferredSize(new java.awt.Dimension(20, 22));
        txtFieldMinutesStopwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldMinutesStopwatchActionPerformed(evt);
            }
        });

        jLabel2.setText(":");

        labelIntroEnterPages.setText("Супер! А колко страници искаш да прочетеш?");

        EnterPages.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EnterPages.setMaximumSize(new java.awt.Dimension(55, 22));
        EnterPages.setMinimumSize(new java.awt.Dimension(55, 22));
        EnterPages.setPreferredSize(new java.awt.Dimension(55, 22));
        EnterPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPagesActionPerformed(evt);
            }
        });

        buttonStartingBigTimer.setText("Го го го!");
        buttonStartingBigTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartingBigTimerActionPerformed(evt);
            }
        });

        labelShowingTimeRequired.setText("Окей, това прави ххч:ххм:ххс. Готова?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(txtFieldMinutesStopwatch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldSecondsStopwatch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(startStop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(labelIntroStopwatch, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EnterPages, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelIntroEnterPages)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelShowingTimeRequired)
                        .addGap(101, 101, 101))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonStartingBigTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelIntroStopwatch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldMinutesStopwatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldSecondsStopwatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(startStop))
                .addGap(18, 18, 18)
                .addComponent(labelIntroEnterPages)
                .addGap(18, 18, 18)
                .addComponent(EnterPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelShowingTimeRequired)
                .addGap(11, 11, 11)
                .addComponent(buttonStartingBigTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldSecondsStopwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSecondsStopwatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSecondsStopwatchActionPerformed

    private void txtFieldMinutesStopwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldMinutesStopwatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldMinutesStopwatchActionPerformed

    private void startStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopActionPerformed
        if(startStop.isSelected()){
            startStop.setText("Стоп");
            stopwatch.scheduleAtFixedRate(stopwatchTask, 0, 100);
            
        }
        else{
            stopwatch.cancel();
            startStop.setText("Старт");
            EnterPages.setVisible(true);
            labelIntroEnterPages.setVisible(true);
        }
    }//GEN-LAST:event_startStopActionPerformed

    private void EnterPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPagesActionPerformed
        Integer valueOfEnteredPages = Integer.valueOf(EnterPages.getText());
        if(valueOfEnteredPages>0){
            minutesCounterStopwatch = minutesCounterStopwatch*valueOfEnteredPages;
            secondsCounterStopwatch = (secondsCounterStopwatch*valueOfEnteredPages)-valueOfEnteredPages;
            minutesCounterStopwatch+= secondsCounterStopwatch/60;
            secondsCounterStopwatch = secondsCounterStopwatch%60;
            hoursCounterStopwatch = minutesCounterStopwatch/60;
            minutesCounterStopwatch = minutesCounterStopwatch%60;
            labelShowingTimeRequired.setText("Окей, това прави "+hoursCounterStopwatch+"ч:"+minutesCounterStopwatch+"м:"+secondsCounterStopwatch+"с. Готова?");
            labelShowingTimeRequired.setVisible(true);
            buttonStartingBigTimer.setVisible(true);
        }
    }//GEN-LAST:event_EnterPagesActionPerformed

    private void buttonStartingBigTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartingBigTimerActionPerformed
        Reading form = new Reading();
        form.txtFieldHoursBigTimer.setText(""+hoursCounterStopwatch);
        form.txtFieldMinutesBigTimer.setText(""+minutesCounterStopwatch);
        form.txtFieldSecondsBigTimer.setText(""+secondsCounterStopwatch);
        form.secondsCounterBigTimer = secondsCounterStopwatch;
        form.minutesCounterBigTimer = minutesCounterStopwatch;
        form.hoursCounterBigTimer = hoursCounterStopwatch;
        form.buttonMain.setVisible(false);
        form.buttonMain.doClick();
        form.setVisible(true);
        
    }//GEN-LAST:event_buttonStartingBigTimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EnterPages;
    private javax.swing.JButton buttonStartingBigTimer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelIntroEnterPages;
    private javax.swing.JLabel labelIntroStopwatch;
    private javax.swing.JLabel labelShowingTimeRequired;
    private javax.swing.JToggleButton startStop;
    private javax.swing.JTextField txtFieldMinutesStopwatch;
    private javax.swing.JTextField txtFieldSecondsStopwatch;
    // End of variables declaration//GEN-END:variables
}
